#!/usr/bin/env bash
# Prompt for config and write .env. Never commit .env.

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

echo "March Madness V1 - Setup configuration"
echo "Values will be written to $ENV_FILE"
echo ""

read -p "CBB_API_BASE_URL [https://api.collegebasketballdata.com]: " CBB_API_BASE_URL
CBB_API_BASE_URL=${CBB_API_BASE_URL:-https://api.collegebasketballdata.com}

read -p "CBB_API_KEY: " CBB_API_KEY
read -p "CBB_API_SECRET: " CBB_API_SECRET

read -p "STATICS_BASE_URL (Statics API base, e.g. https://your-statics.com): " STATICS_BASE_URL
read -p "STATICS_API_KEY: " STATICS_API_KEY
read -p "STATICS_TABLE_NAME [Statics]: " STATICS_TABLE_NAME
STATICS_TABLE_NAME=${STATICS_TABLE_NAME:-Statics}

read -p "TWILIO_ACCOUNT_SID: " TWILIO_ACCOUNT_SID
read -p "TWILIO_AUTH_TOKEN: " TWILIO_AUTH_TOKEN
read -p "TWILIO_PHONE_NUMBER (e.g. +15551234567): " TWILIO_PHONE_NUMBER

read -p "AWS_REGION [us-east-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-us-east-1}
read -p "S3_BUCKET_NAME (for static site): " S3_BUCKET_NAME

cat > "$ENV_FILE" << EOF
# Generated by setup_config.sh - do not commit
CBB_API_BASE_URL=$CBB_API_BASE_URL
CBB_API_KEY=$CBB_API_KEY
CBB_API_SECRET=$CBB_API_SECRET
STATICS_BASE_URL=$STATICS_BASE_URL
STATICS_API_KEY=$STATICS_API_KEY
STATICS_TABLE_NAME=$STATICS_TABLE_NAME
TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
TWILIO_PHONE_NUMBER=$TWILIO_PHONE_NUMBER
AWS_REGION=$AWS_REGION
S3_BUCKET_NAME=$S3_BUCKET_NAME
EOF

echo ""
echo "Wrote $ENV_FILE"
echo "Copy .env.example to share structure (without secrets)."
